import React, { useState, useEffect, useContext } from 'react';
import { Container, Row, Col, Card, Spinner, Button } from 'react-bootstrap';
import DAOImage from '../../assets/dao.png';
import TableImage from '../../assets/table.png';
import CheckNFTModal from './check-nft-modal';
import { dao_8yg_backend as backend } from '../../../declarations/dao_8yg_backend';
import { ConnectButton, useConnect } from "@connect2ic/react";

const Home = () => {
  
  const [isLoading, setIsLoading] = useState(true);
  const [showCheckWalletModal, setShowCheckWalletModal] = useState(false);
  const [data, setData] = useState(0);
  const [totalSupply, setTotalSupply] = useState(0);
  const { isConnected } = useConnect();

  useEffect(() => {
    const fetchData = async () => {
      let homeDTO = await backend.getHomeDTO();
      setData(homeDTO);
      setIsLoading(false);
      let supply = await backend.getTotalSupply();
      setTotalSupply(supply);
    };
    fetchData();
  }, []);

  const hideCheckWalletModal = async () => {
    setShowCheckWalletModal(false); 
  };

  return (
    isLoading ? (
      <div className="customOverlay d-flex flex-column align-items-center justify-content-center">
      <Spinner animation="border" />
      <p className='text-center mt-1'>Loading</p>
    </div>) : 
    (
      <Container className="flex-grow-1 my-5">
        <Row className="text-center">
          <Col>
            <h4 className='gold-header'>PROFIT GENERATED BY THE DAO</h4>
          </Col>
        </Row>
        <Row className="mb-4">
          <Col className="text-center border-right border-white">
            <h4 className='numerical-text detail-text'>ICP {data.profit_icp.toLocaleString()}</h4>
          </Col>
          <Col className="text-center">
            <h4 className='numerical-text detail-text'>${data.profit_usd.toLocaleString()}</h4>
          </Col>
        </Row>
        <Row>
          <Col className="text-center">
            <h6 className='purple-subheader'>PURCHASED NFTs</h6>
            <p className='numerical-text detail-text'>{data.purchased_nfts.toLocaleString()}</p>
          </Col>
          <Col className="text-center">
            <h6 className='purple-subheader'>SOLD NFTs</h6>
            <p className='numerical-text detail-text'>{data.sold_nfts.toLocaleString()}</p>
          </Col>
        </Row>
        <Row className="mb-4">
          <Col className="text-center">
            <h6 className='purple-subheader'>OWNED NFTs</h6>
            <p className='numerical-text detail-text'>{data.owned_NFTs.toLocaleString()}</p>
          </Col>
          <Col className="text-center">
            <h6 className='purple-subheader'>FLOOR PRICE VALUE</h6>
            <p className='numerical-text detail-text'>${data.floor_price.toLocaleString()}</p>
          </Col>
        </Row>
        <Row>
          <Col className="text-center">
            <h6 className='blue-subheader'>TOTAL SUPPLY</h6>
            <p className='numerical-text detail-text'>{totalSupply.toLocaleString()}</p>
          </Col>
          <Col className="text-center">
            <h6 className='blue-subheader'>PRICE 8YG TOKEN</h6>
            <p className='numerical-text detail-text'>${data.price_8yg.toLocaleString()}</p>
          </Col>
        </Row>
        <Row className="mb-4">
          <Col className="text-center">
            <h6 className='blue-subheader'>MARKET CAP</h6>
            <p className='numerical-text detail-text'>${data.market_cap.toLocaleString()}</p>
          </Col>
          <Col className="text-center">
            <h6 className='blue-subheader'>VOLUME</h6>
            <p className='numerical-text detail-text'>${data.volume.toLocaleString()}</p>
          </Col>
        </Row>
        <Row>
          <Col md={6}>
            <img src={DAOImage} alt="8yg" className='mt-2 mb-4' style={{ maxWidth: '100%', maxHeight: '100%', marginRight: '10px' }} />
            <img src={TableImage} alt="8yg" className='mt-2 mb-4' style={{ maxWidth: '100%', maxHeight: '100%', marginRight: '10px' }} />
          </Col>
          <Col md={6}>
            <Row>
              <Col md={12}>
                <h1>8 Years Gang DAO</h1>
                
                <p className='mt-4 mb-4'><b>1. Stake Your 8 Years Gang NFTs</b>
                  <br /><br />
                  By staking your 8 Years Gang NFTs here, you can participate in proposals or start a new one. There is no minimum duration, which means you can unstake or restake your NFTs at any time.
                </p>
                
                <p className='mt-4 mb-4'><b>2. Participate in Proposals or Start a New Proposal</b>
                  <br /><br />
                  Your voting power is determined based on the number of 8 Years Gang NFTs you have staked. The higher your voting power, the greater the weight of your vote in each proposal.
                </p>
                
                <p className='mt-4 mb-4'><b>3 & 4. Earn $8YG Tokens</b>
                  <br /><br />
                  Once the DAO successfully sells an NFT and generates revenue, the smart contract uses these earnings to purchase $8YG Tokens and distributes them to all participants who took part in the proposal. The distribution of tokens takes into account the voting power of each individual member who participated. The higher your voting power, the greater your earnings.
                  <br /><br />
                  Staking your NFTs allows you to actively participate in shaping the direction of the DAO and be rewarded with $8YG Tokens based on your contribution. It's an opportunity to engage in decision-making and benefit from the success of the DAO's activities.

                </p>
                {isConnected && 
                  <Button className="btn btn-sm mt-3 mb-4" onClick={() => setShowCheckWalletModal(true)}>View DAO NFT Wallet</Button>
                }

                
                {!isConnected &&
                  <ConnectButton />
                }
                
              </Col>
            </Row>
          </Col>
        </Row>

        {showCheckWalletModal && 
          <CheckNFTModal
            show={showCheckWalletModal}
            onHide={hideCheckWalletModal}
          />
        }
      </Container>
    )
  );
};

export default Home;
