import React, { useState, useEffect, useContext } from 'react';
import { Container, Row, Col, Card, Spinner, Button } from 'react-bootstrap';
import AuctionImage from '../../assets/8YGAuction.jpg';
import CheckNFTModal from './check-nft-modal';
import { dao_8yg_backend as backend } from '../../../declarations/dao_8yg_backend';

const Home = () => {
  
  const [isLoading, setIsLoading] = useState(true);
  const [showCheckWalletModal, setShowCheckWalletModal] = useState(false);
  const [profitICP, setProfitICP] = useState(0);
  const [profitUSD, setProfitUSD] = useState(0);
  const [data, setData] = useState(0);
  const [totalSupply, setTotalSupply] = useState(0);
  
  useEffect(() => {
    const fetchData = async () => {
      let homeDTO = await backend.getHomeDTO();
      setData(homeDTO);
      console.log(homeDTO);
      setIsLoading(false);
      let supply = await backend.getTotalSupply();
      setTotalSupply(supply);
    };
    fetchData();
  }, []);

  const hideCheckWalletModal = async () => {
    setShowCheckWalletModal(false); 
  };

  return (
    isLoading ? (
      <div className="customOverlay d-flex flex-column align-items-center justify-content-center">
      <Spinner animation="border" />
      <p className='text-center mt-1'>Loading</p>
    </div>) : 
    (
      <Container className="flex-grow-1 my-5">
        <Row className="text-center">
          <Col>
            <h4 className='gold-header'>PROFIT GENERATED BY THE DAO</h4>
          </Col>
        </Row>
        <Row className="mb-4">
          <Col className="text-center border-right border-white">
            <h4 className='numerical-text detail-text'>ICP {data.profit_icp.toLocaleString()}</h4>
          </Col>
          <Col className="text-center">
            <h4 className='numerical-text detail-text'>${data.profit_usd.toLocaleString()}</h4>
          </Col>
        </Row>
        <Row>
          <Col className="text-center">
            <h6 className='purple-subheader'>PURCHASED NFTs</h6>
            <p className='numerical-text detail-text'>{data.purchased_nfts.toLocaleString()}</p>
          </Col>
          <Col className="text-center">
            <h6 className='purple-subheader'>SOLD NFTs</h6>
            <p className='numerical-text detail-text'>{data.sold_nfts.toLocaleString()}</p>
          </Col>
        </Row>
        <Row className="mb-4">
          <Col className="text-center">
            <h6 className='purple-subheader'>OWNED NFTs</h6>
            <p className='numerical-text detail-text'>{data.owned_NFTs.toLocaleString()}</p>
          </Col>
          <Col className="text-center">
            <h6 className='purple-subheader'>FLOOR PRICE VALUE</h6>
            <p className='numerical-text detail-text'>${data.floor_price.toLocaleString()}</p>
          </Col>
        </Row>
        <Row>
          <Col className="text-center">
            <h6 className='blue-subheader'>TOTAL SUPPLY</h6>
            <p className='numerical-text detail-text'>{totalSupply.toLocaleString()}</p>
          </Col>
          <Col className="text-center">
            <h6 className='blue-subheader'>PRICE 8YG TOKEN</h6>
            <p className='numerical-text detail-text'>${data.price_8yg.toLocaleString()}</p>
          </Col>
        </Row>
        <Row className="mb-4">
          <Col className="text-center">
            <h6 className='blue-subheader'>MARKET CAP</h6>
            <p className='numerical-text detail-text'>${data.market_cap.toLocaleString()}</p>
          </Col>
          <Col className="text-center">
            <h6 className='blue-subheader'>VOLUME</h6>
            <p className='numerical-text detail-text'>${data.volume.toLocaleString()}</p>
          </Col>
        </Row>
        <Row>
          <Col md={6}>
            <img src={AuctionImage} alt="8yg" className='mt-2 mb-4' style={{ maxWidth: '100%', maxHeight: '100%', marginRight: '10px' }} />
          </Col>
          <Col md={6}>
            <Row>
              <Col md={12}>
                <h1>Welcome</h1>
                <p className='mt-4 mb-4'>8 Years Gang NFT holders will be able to stake their NFTs within this DAO. Initially this will enable them to participate in governance of the 8YG wallet and receive rewards based on the DAO's profit.</p>
                
                <Button className="btn btn-sm mt-3 mb-4" onClick={() => setShowCheckWalletModal(true)}>View 8YG Wallet</Button>
                
                <p className='mb-4'>We aim to introduce various mechanisms to maximise the rewards associated with the gang members you own, check back here in the future for further updates.</p>
              </Col>
            </Row>
          </Col>
        </Row>

        {showCheckWalletModal && 
          <CheckNFTModal
            show={showCheckWalletModal}
            onHide={hideCheckWalletModal}
          />
        }
      </Container>
    )
  );
};

export default Home;
